---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.240-192.168.0.245
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-announce-ip
  namespace: metallb-system
---