apiVersion: v1
kind: Pod
metadata:
  name: pg-client
spec:
  restartPolicy: Never
  containers:
    - name: pg-client
      image: postgres:15-alpine
      command: ["sleep", "3600"]
      env:
        - name: CLIENTPASSWORD
          valueFrom:
            secretKeyRef:
              name: syn-insights-postgresql-app
              key: password
        - name: CLIENTUSERNAME
          valueFrom:
            secretKeyRef:
              name: syn-insights-postgresql-app
              key: username
        - name: OWNERPASSWORD
          valueFrom:
            secretKeyRef:
              name: syn-insights-postgresql-superuser
              key: password
        - name: OWNERUSERNAME
          valueFrom:
            secretKeyRef:
              name: syn-insights-postgresql-superuser
              key: username
